### ISSUE TITLE
技能點問題

### ISSUE THREAD

**Issue by AILUtheCAT** [Lorex/tsjtw#12]
![image](https://user-images.githubusercontent.com/37771244/112437471-f2e00f80-8d81-11eb-9405-776596c5f186.png)
吹吹這麼多次了都滿足技能點了卻不能買技能 哭哭喔QQ
我要推坑了ㄛ

**Comment by tw-JordanChen** [comment]
這個跟我回報的 #4 是相同的問題

**Comment by Lorex** [comment]
與 #4 一起處理，這串 issue 會先關掉。
