### ISSUE TITLE
刪文後每秒數字跳動有誤

### ISSUE THREAD

**Issue by RayHBR** [Lorex/tsjtw#13]
成功達到450位數左右刪文 但刪文後數字的跳動並沒有每0.094秒跳一次 應該是 setInterval 有問題吧...

![擷取](https://user-images.githubusercontent.com/39508238/112437566-0db28400-8d82-11eb-9c31-d357d8f32065.JPG)

**Comment by Lorex** [comment]
這邊應該是讀檔順序的問題，已經解決，如果還有問題再另外開串XD
