### ISSUE TITLE
等級500刪文後自動吹間隔變負數

### ISSUE THREAD

**Issue by ejutyxew** [Lorex/tsjtw#16]
![-0.044](https://user-images.githubusercontent.com/81350358/112440627-86670f80-8d85-11eb-82a8-20d40251dcc8.png)
大大是不是發明了時光機，這樣玩下去會時間倒流嗎？

**Comment by karakarasuuuu** [comment]
![1A5D79A8-5075-4339-865F-54EBCF6F9265](https://user-images.githubusercontent.com/19412420/112458751-17df7d00-8d98-11eb-9d23-335e975ddb8c.jpeg)

**Comment by Lorex** [comment]
這是顯示問題，已經修正XD
