### ISSUE TITLE
BigNumber 捨入問題

### ISSUE THREAD

**Issue by tw-JordanChen** [Lorex/tsjtw#4]
當啟用 autoBlow 後，畫面上顯示的技術點可能因有捨入，所以當顯示值 = 欲購買的道具時，會發生無法購買的情況

我JS小白，不會自己改不然就送PR了 QQ

**Comment by Lorex** [comment]
這部分我會把顯示的捨入方法改為無條件捨去，這樣應該會好一些

**Comment by Lorex** [comment]
問題已修正。
