### ISSUE TITLE
iPhone Safari無法顯示

### ISSUE THREAD

**Issue by hsiungyuu** [Lorex/tsjtw#53]
重整過好幾次了
![image](https://user-images.githubusercontent.com/73240633/112636001-7891b700-8e77-11eb-9e99-0a657d8dbde3.png)

**Comment by tico88612** [comment]
正常模式打開也是失敗  
但開無痕模式是可以的  
我推測是 main.js Cache 的問題
![image](https://user-images.githubusercontent.com/17496418/112708653-39527d00-8eee-11eb-96b6-7a02f1d0d5a6.png)

上述圖片來看 main.js 讀取到舊版的程式  
這種情況可以清理 Web Browser 馬上解決（不過代價很高，很多都要重登）  
#58 我加入 version 檢查防止 cache
